"""Add text_vector to Product

Revision ID: 5bbeef2e4f6e
Revises: 7ad344978fd0
Create Date: 2025-11-16 16:37:35.451979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbeef2e4f6e'
down_revision: Union[str, Sequence[str], None] = '7ad344978fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('text_vector', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'text_vector')
    # ### end Alembic commands ###
