"""Add text_vector to Product

Revision ID: 636243cbdb6f
Revises: 5bbeef2e4f6e
Create Date: 2025-11-16 16:49:01.975367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636243cbdb6f'
down_revision: Union[str, Sequence[str], None] = '5bbeef2e4f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
